refactor: moving consul access and role interface
edgexfoundry/go-mod-secrets pull request #163
Opened 2022-10-12 00:12 UTC by ItsRico

Moving configureConsulAccess and createRole to go-mod-secrets to consolidate consul API.

Closes: #3227

Signed-off-by: Rico Chavez-Lopez <rchavezlopez@ucdavis.edu>

If your build fails due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-secrets/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [ ] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

## New Dependency Instructions (If applicable)

2022-10-12 00:29 UTC, bnevis-i submitted a review, later dismissed
LGTM.  Merging hold until have corrected edgex-go PR to test against.

2022-10-12 00:50 UTC, jim-wang-intel submitted a review, later dismissed

2022-10-18 18:43 UTC, lenny-intel requested changes
Code looks good, but need to change all usages of  `registry` to be `Consul`. I have flagged a bunch of them, but there are more.

2022-10-18 18:43 UTC, lenny-intel commented on pkg/types/registryroles.go
> +type RegistryTokenType string
Chhange all use of term `registry` to `Consul` in code and comments
```suggestion
type ConsulTokenType string
```

2022-10-18 18:43 UTC, lenny-intel commented on pkg/types/registryroles.go
> +type RegistryRole struct {
```suggestion
type ConsulRole struct {
```

2022-10-18 18:43 UTC, lenny-intel commented on pkg/types/registryroles.go
> +func NewRegistryRole(name string, tokenType RegistryTokenType, policies []Policy, localUse bool) RegistryRole {
```suggestion
func NewConsulRole(name string, tokenType ConsulTokenType, policies []Policy, localUse bool) ConsulRole {
```

2022-10-18 18:43 UTC, lenny-intel commented on pkg/types/registryroles.go
> +	return RegistryRole{
```suggestion
	return ConsulRole{
```

2022-10-18 18:43 UTC, lenny-intel commented on pkg/types/registryroles.go
> +/*******************************************************************************
change file name to consulroles.go

2022-10-18 18:43 UTC, lenny-intel commented on internal/pkg/vault/management.go
> +		RegistryAddress   string `json:"address"`
Here an others below.

```suggestion
		ConsulAddress   string `json:"address"`
```

2022-10-18 18:43 UTC, lenny-intel commented on internal/pkg/vault/management.go
> +func (c *Client) ConfigureConsulAccess(secretStoreToken string, bootstrapACLToken string, registryHost string, registryPort int) error {
```suggestion
func (c *Client) ConfigureConsulAccess(secretStoreToken string, bootstrapACLToken string, consulHost string, consulPort int) error {
```

2022-10-19 00:47 UTC, ItsRico commented
Updated all references of registry to consul

2022-10-19 01:46 UTC, lenny-intel approved these changes
LGTM, time to take out of draft?

2022-10-19 01:46 UTC, lenny-intel commented on internal/pkg/vault/management.go
> +// CreateRole creates a secret store role that can be used to generate Consul tokens
```suggestion
// CreateRole creates a Consul role that can be used to generate Consul tokens
```

2022-10-19 01:47 UTC, lenny-intel requested changes
One minor tweak needed

2022-10-19 02:14 UTC, ItsRico commented on internal/pkg/vault/management.go
> +// CreateRole creates a secret store role that can be used to generate Consul tokens
updated

2022-10-19 13:30 UTC, lenny-intel approved these changes
LGTM

2022-10-19 13:55 UTC, bnevis-i approved these changes

2022-10-19 13:56 UTC, merged