refactor!: Refactor all usages of path to be secretName in APIs and I…
edgexfoundry/go-mod-secrets pull request #180
Opened 2023-02-09 18:32 UTC by vli11

…nsecureSecrets configuration

BREAKING CHANGE: Refactor all usages of path to be secretName

Signed-off-by: Valina Li <valina.li@intel.com>

If your build fails due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-secrets/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions
make test

## New Dependency Instructions (If applicable)

2023-02-09 19:24 UTC, bnevis-i commented
I think the intention was to also rename parameters as well:

https://github.com/edgexfoundry/go-mod-secrets/blob/main/secrets/interfaces.go

2023-02-09 20:16 UTC, lenny-intel commented
> I think the intention was to also rename parameters as well:

Correct!

2023-02-14 20:42 UTC, lenny-intel requested changes

2023-02-14 20:42 UTC, lenny-intel commented on internal/pkg/vault/secrets_test.go
> +	testSecretName3 = "/secret3"
We need the code to not require `/` at beginning of the name. The internal code should add it.
That should be done here: https://github.com/edgexfoundry/go-mod-secrets/blob/main/pkg/types/config.go#L50
and subPath should be changed everywhere.

2023-02-15 16:50 UTC, lenny-intel requested changes

2023-02-15 16:50 UTC, lenny-intel commented on pkg/types/config.go
> +	SecretName string
This stays as `Path` since it is the actual Vault path to the service SecretStore. Maybe change to this:
```suggestion
	StoreBasePath string
```

2023-02-15 16:50 UTC, lenny-intel commented on pkg/types/config.go
> +	return c.BuildURL(c.SecretName + subPath)
This resolves the need to include the leading `/` in the secretName
```suggestion
	return c.BuildURL(fmt.Sprintf("%s/%s,c.StoreBasePath, secretName)
```

2023-02-15 16:50 UTC, lenny-intel commented on pkg/types/config.go
>  func (c SecretConfig) BuildSecretsPathURL(subPath string) (string, error) {
```suggestion
func (c SecretConfig) BuildSecretsPathURL(secrenName string) (string, error) {
```

2023-02-15 16:50 UTC, lenny-intel commented on pkg/types/config.go
>  // subPath is the location of the secrets in the secrets engine
```suggestion
// BuildSecretsPathURL constructs a URL to the service's secret with in it's secret store
// secretName is the name of the secret in the service's secret store
```

2023-02-15 16:56 UTC, lenny-intel commented
Also please update to use latest core contracts which has @marcpfuller's DTO changes that go along with these.

2023-02-22 17:10 UTC, lenny-intel requested changes

2023-02-22 17:10 UTC, lenny-intel commented on pkg/listener/poll_test.go
> +			secretName:        "/unknownsecretName",
```suggestion
			secretName:        "unknownsecretName",
```

2023-02-22 17:10 UTC, lenny-intel commented on pkg/listener/poll_test.go
> +			expectedErrorType: pkg.NewErrSecretStore("incorrect secretName for storing secrets: /unknownsecretName"),
```suggestion
			expectedErrorType: pkg.NewErrSecretStore("incorrect secretName for storing secrets: unknownsecretName"),
```

2023-02-22 17:10 UTC, lenny-intel commented on pkg/listener/poll_test.go
> +			secretName:        "/unknownsecretName",
```suggestion
			secretName:        "unknownsecretName",
```

2023-02-22 17:10 UTC, lenny-intel commented on pkg/types/config.go
> +func (c SecretConfig) BuildSecretsPathURL(secretName string) (string, error) {
```suggestion
// BuildSecretNameURL constructs a URL to the service's secret with in it's secret store
// secretName is the name of the secret in the service's secret store
func (c SecretConfig) BuildSecretNameURL(secretName string) (string, error) {
```

2023-02-22 17:10 UTC, lenny-intel commented on pkg/types/config.go
> +func (c SecretConfig) BuildRequestPathURL(subPath string) (string, error) {
Also need to add comment for the function

```suggestion
func (c SecretConfig) BuildRequestURL(subPath string) (string, error) {
```

2023-02-22 17:10 UTC, lenny-intel commented on pkg/types/config_test.go
> +	cfgWithPath := SecretConfig{Host: "localhost", Port: 8080, Protocol: "http", StoreBasePath: "/ping"}
Humm, now that we see that SecretConfig is used for both Secrets and general Vault requests, not sure `StoreBasePath` is the correct name. Maybe just `basePath`

2023-02-22 17:16 UTC, lenny-intel commented on internal/pkg/vault/secrets.go
> +func (c *Client) getAllPaths(secretName string) ([]string, error) {
look like this implements the `GetKeys`, so the name in the comment is correct. Only called from `GetKeys`. So name of the function just needs to be tweaked appropriately. 
```suggestion
func (c *Client) getAllKeys(secretName string) ([]string, error) {
```

2023-02-22 18:18 UTC, lenny-intel requested changes

2023-02-22 18:18 UTC, lenny-intel commented on secrets/interfaces.go
> +	GetKeys(secretName string) ([]string, error)
```suggestion
	GetSecretNames() ([]string, error)
```

2023-02-22 18:18 UTC, lenny-intel commented on internal/pkg/vault/secrets.go
> +func (c *Client) GetKeys(secretName string) ([]string, error) {
```suggestion
func (c *Client) GetSecretNames() ([]string, error) {
```

2023-02-22 18:18 UTC, lenny-intel commented on internal/pkg/vault/secrets.go
> +	data, err := c.getAllPaths(secretName)
```suggestion
	data, err := c.getAllSecretNames()
```

2023-02-22 18:18 UTC, lenny-intel commented on internal/pkg/vault/secrets.go
> +func (c *Client) getAllPaths(secretName string) ([]string, error) {
```suggestion
func (c *Client) getAllSecretNames() ([]string, error) {
```

2023-02-22 18:18 UTC, lenny-intel commented on internal/pkg/vault/secrets.go
> +	url, err := c.Config.BuildSecretsPathURL(secretName)
```suggestion
	url, err := c.Config.BuildSecretsPathURL("")
```

2023-02-22 20:31 UTC, lenny-intel requested changes

2023-02-22 20:31 UTC, lenny-intel commented on secrets/interfaces.go
> +	GetSecretNames(secretName string) ([]string, error)
No parameter needed as it gets all the secret names from the base path for the Store
```suggestion
	GetSecretNames() ([]string, error)
```

2023-02-22 20:31 UTC, lenny-intel commented on internal/pkg/vault/secrets.go
> +func (c *Client) GetSecretNames(secretName string) ([]string, error) {
```suggestion
func (c *Client) GetSecretNames() ([]string, error) {
```

2023-02-22 20:31 UTC, lenny-intel commented on internal/pkg/vault/secrets.go
> +	data, err := c.getAllKeyNames(secretName)
```suggestion
	data, err := c.getAllKeyNames("")
```

2023-02-23 00:30 UTC, lenny-intel approved these changes

2023-02-23 00:33 UTC, merged