feat(security): Add Generate Registry Token API for secretstore client
edgexfoundry/go-mod-secrets pull request #97
Opened 2021-03-25 23:16 UTC by jim-wang-intel

Added vault's /consul/creds/<serviceKey> API  to generate consul token

Closes: #95

Signed-off-by: Jim Wang <yutsung.jim.wang@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x ] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide
- [x ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

N/A: no API to generate consul token

Issue Number:  #95 

## What is the new behavior?
New management API GenerateRegistryToken is added on `SecretstoreClient` that can be used to generate consul token

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

## Are there any new imports or modules? If so, what are they used for and why?

## Are there any specific instructions or things that should be known prior to reviewing?

## Other information

2021-03-26 00:02 UTC, lenny-intel requested changes

2021-03-26 00:02 UTC, lenny-intel commented on secrets/interfaces.go
> +	GenerateRegistryToken(token, serviceKey string) (string, error)
Change to GenerateConsulToken

2021-03-26 00:17 UTC, jim-wang-intel commented on internal/pkg/vault/management.go
> +func (c *Client) GenerateRegistryToken(mgmtToken, serviceKey string) (string, error) {
ok, i'll change the naming

2021-03-29 21:53 UTC, jim-wang-intel commented on internal/pkg/vault/management.go
> +func (c *Client) GenerateRegistryToken(mgmtToken, serviceKey string) (string, error) {
fix

2021-03-29 21:53 UTC, jim-wang-intel commented on internal/pkg/vault/management.go
> +		return emptyToken, pkg.NewErrSecretStore("missing mgmt token for generating registry token")
fix

2021-03-29 21:53 UTC, jim-wang-intel commented on secrets/interfaces.go
> +	GenerateRegistryToken(token, serviceKey string) (string, error)
fix

2021-03-29 23:15 UTC, lenny-intel approved these changes
LGTM

2021-03-29 23:16 UTC, merged